/**
 * UK Cities and location utilities
 */

export const UK_CITIES = [
    'Aberdeen',
    'Bath',
    'Belfast',
    'Birmingham',
    'Bradford',
    'Brighton',
    'Bristol',
    'Cambridge',
    'Canterbury',
    'Cardiff',
    'Carlisle',
    'Chelmsford',
    'Chester',
    'Chichester',
    'Coventry',
    'Derby',
    'Dundee',
    'Durham',
    'Edinburgh',
    'Ely',
    'Exeter',
    'Glasgow',
    'Gloucester',
    'Hereford',
    'Inverness',
    'Kingston upon Hull',
    'Lancaster',
    'Leeds',
    'Leicester',
    'Lichfield',
    'Lincoln',
    'Liverpool',
    'London',
    'Manchester',
    'Newcastle upon Tyne',
    'Newport',
    'Norwich',
    'Nottingham',
    'Oxford',
    'Peterborough',
    'Plymouth',
    'Portsmouth',
    'Preston',
    'Ripon',
    'Salford',
    'Salisbury',
    'Sheffield',
    'Southampton',
    'St Albans',
    'Stirling',
    'Stoke-on-Trent',
    'Sunderland',
    'Swansea',
    'Truro',
    'Wakefield',
    'Wells',
    'Westminster',
    'Winchester',
    'Wolverhampton',
    'Worcester',
    'York',
] as const;

export function isLondon(city: string | null | undefined): boolean {
    if (!city) return false;
    return city.toLowerCase() === 'london' || city.toLowerCase() === 'westminster';
}
