import { BOROUGHS } from './Boroughs';

/**
 * Curated list of UK cities and towns across England, Scotland, Wales, and Northern Ireland.
 * London is included as a top-level option; selecting it triggers borough sub-selection.
 */
export const UK_CITIES = [
  'London',
  'Manchester',
  'Birmingham',
  'Leeds',
  'Glasgow',
  'Liverpool',
  'Bristol',
  'Sheffield',
  'Edinburgh',
  'Cardiff',
  'Belfast',
  'Newcastle upon Tyne',
  'Nottingham',
  'Brighton',
  'Leicester',
  'Coventry',
  'Hull',
  'Bradford',
  'Stoke-on-Trent',
  'Wolverhampton',
  'Derby',
  'Plymouth',
  'Reading',
  'Portsmouth',
  'Northampton',
  'Luton',
  'Aberdeen',
  'Milton Keynes',
  'Swindon',
  'Swansea',
  'Oxford',
  'Cambridge',
  'Ipswich',
  'Norwich',
  'Exeter',
  'Bournemouth',
  'Peterborough',
  'Slough',
  'Gloucester',
  'Cheltenham',
  'Bath',
  'York',
  'Lincoln',
  'Chester',
  'Durham',
  'Canterbury',
  'Lancaster',
  'Salisbury',
  'Winchester',
  'Worcester',
  'Hereford',
  'Carlisle',
  'Preston',
  'Blackpool',
  'Blackburn',
  'Burnley',
  'Bolton',
  'Oldham',
  'Rochdale',
  'Stockport',
  'Warrington',
  'Chesterfield',
  'Doncaster',
  'Rotherham',
  'Barnsley',
  'Huddersfield',
  'Wakefield',
  'Halifax',
  'Dundee',
  'Inverness',
  'Stirling',
  'Perth',
  'Dunfermline',
  'Kirkcaldy',
  'Glenrothes',
  'Ayr',
  'Kilmarnock',
  'Paisley',
  'East Kilbride',
  'Livingston',
  'Cumbernauld',
  'Hamilton',
  'Newport',
  'Wrexham',
  'Bangor',
  'Coleraine',
  'Derry',
  'Lisburn',
  'Newry',
  'Armagh',
  'Newtownabbey',
  'Craigavon',
  'Castlereagh',
  'Ballymena',
  'Newtownards',
  'Carrickfergus',
  'Larne',
  'Antrim',
  'Omagh',
  'Enniskillen',
  'Strabane',
  'Downpatrick',
  'Colchester',
  'Southend-on-Sea',
  'Maidstone',
  'Guildford',
  'Epsom',
  'Redhill',
  'Crawley',
  'Eastbourne',
  'Hastings',
  'Basingstoke',
  'Poole',
  'Weymouth',
  'Torquay',
  'Truro',
  'Falmouth',
  'Penzance',
  'Scarborough',
  'Whitby',
  'Harrogate',
  'Ripon',
  'Skipton',
  'Kendal',
  'Barrow-in-Furness',
  'Whitehaven',
  'Workington',
  'Keswick',
  'Ambleside',
  'Windermere',
] as const;

export type UKCity = (typeof UK_CITIES)[number];

export function isLondon(city: string): boolean {
  return city === 'London';
}

export { BOROUGHS };
