version = 0.1

[default.deploy.parameters]
stack_name = "tuberush-daily-games"
resolve_s3 = true
s3_prefix = "tuberush-daily-games"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "SecretName=\"tuberush/daily-games\" ScheduleExpression=\"cron(0 2 * * ? *)\""
image_repositories = []

[default.global.parameters]
region = "eu-west-1"
